/*
* generated by Xtext
*/
package fzi.mottem.ptspec.dsl;

//import org.eclipse.emf.ecore.*;
//import org.eclipse.ocl.ecore.delegate.*;

import com.google.inject.Injector;

/**
 * Initialization support for running Xtext languages 
 * without equinox extension registry
 */
public class PTSpecStandaloneSetup extends PTSpecStandaloneSetupGenerated
{

	public static void doSetup()
	{
		new PTSpecStandaloneSetup().createInjectorAndDoEMFRegistration();
	}
		
	@Override
	public void register(Injector injector)
	{
//		String oclDelegateURI = OCLDelegateDomain.OCL_DELEGATE_URI;
//		EOperation.Internal.InvocationDelegate.Factory.Registry.INSTANCE.put(oclDelegateURI,
//		    new OCLInvocationDelegateFactory.Global());
//		EStructuralFeature.Internal.SettingDelegate.Factory.Registry.INSTANCE.put(oclDelegateURI,
//		    new OCLSettingDelegateFactory.Global());
//		EValidator.ValidationDelegate.Registry.INSTANCE.put(oclDelegateURI,
//		    new OCLValidationDelegateFactory.Global());
		
		super.register(injector);
	}
	
}

