/*
 * generated by Xtext
 */
package fzi.mottem.ptspec.dsl;

/**
 * Use this class to register components to be used at runtime / without the Equinox extension registry.
 */
public class PTSpecRuntimeModule extends fzi.mottem.ptspec.dsl.AbstractPTSpecRuntimeModule
{

	// Standard bindings originally defined in xtext internal RuntimeModule (i.e. DefaultRuntimeModule)
	// ------------------------------

	@Override
	public Class<? extends org.eclipse.xtext.linking.ILinker> bindILinker()
	{
		return fzi.mottem.ptspec.dsl.linking.PTSpecLazyLinker.class;
	}

	
	// Standard bindings originally defined in generated RuntimeModule (AbstractPTSpecRuntimeModule)
	// (no @Override in some cases, because corresponding entry in MWE file had to be removed)
	// ------------------------------

	// originally contributed by org.eclipse.xtext.generator.validation.ValidatorFragment
	@org.eclipse.xtext.service.SingletonBinding(eager=true)
	public Class<? extends fzi.mottem.ptspec.dsl.validation.PTSpecValidator> bindPTSpecValidator()
	{
		return fzi.mottem.ptspec.dsl.validation.PTSpecValidator.class;
	}

	// originally contributed by org.eclipse.xtext.generator.generator.GeneratorFragment
	public Class<? extends org.eclipse.xtext.generator.IGenerator> bindIGenerator()
	{
		return fzi.mottem.ptspec.dsl.generator.PTSpecGenerator.class;
	}
	
	// originally contributed by org.eclipse.xtext.generator.types.TypesGeneratorFragment
	public Class<? extends org.eclipse.xtext.scoping.IGlobalScopeProvider> bindIGlobalScopeProvider()
	{
		return org.eclipse.xtext.scoping.impl.ImportUriGlobalScopeProvider.class;
	}

	
	// Custom bindings
	// ------------------------------

	public Class<? extends fzi.mottem.ptspec.dsl.scoping.PTSpecSymbolReferenceScopeProvider> bindPTSSymbolReferenceScope()
	{
		return fzi.mottem.ptspec.dsl.scoping.PTSpecSymbolReferenceScopeProvider.class;
	}

	public Class<? extends fzi.mottem.ptspec.dsl.scoping.PTSpecJavaScopeProvider> bindJavaGlobalScopeProvider()
	{
		return fzi.mottem.ptspec.dsl.scoping.PTSpecJavaScopeProvider.class;
	}
	
}
