/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class fzi_mottem_runtime_rti_keil_UVSocketJniJava */

#ifndef _Included_fzi_mottem_runtime_rti_keil_UVSocketJniJava
#define _Included_fzi_mottem_runtime_rti_keil_UVSocketJniJava
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     fzi_mottem_runtime_rti_keil_UVSocketJniJava
 * Method:    load
 * Signature: ()I
 */
JNIEXPORT jint JNICALL Java_fzi_mottem_runtime_rti_keil_UVSocketJniJava_load
  (JNIEnv *, jobject);

/*
 * Class:     fzi_mottem_runtime_rti_keil_UVSocketJniJava
 * Method:    reset
 * Signature: ()I
 */
JNIEXPORT jint JNICALL Java_fzi_mottem_runtime_rti_keil_UVSocketJniJava_reset
  (JNIEnv *, jobject);

/*
 * Class:     fzi_mottem_runtime_rti_keil_UVSocketJniJava
 * Method:    killBreakpoints
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_fzi_mottem_runtime_rti_keil_UVSocketJniJava_killBreakpoints
  (JNIEnv *, jobject);

/*
 * Class:     fzi_mottem_runtime_rti_keil_UVSocketJniJava
 * Method:    init
 * Signature: ()I
 */
JNIEXPORT jint JNICALL Java_fzi_mottem_runtime_rti_keil_UVSocketJniJava_init
  (JNIEnv *, jobject);

/*
 * Class:     fzi_mottem_runtime_rti_keil_UVSocketJniJava
 * Method:    closeConnection
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_fzi_mottem_runtime_rti_keil_UVSocketJniJava_closeConnection
  (JNIEnv *, jobject);

/*
 * Class:     fzi_mottem_runtime_rti_keil_UVSocketJniJava
 * Method:    showUVISION
 * Signature: ()I
 */
JNIEXPORT jint JNICALL Java_fzi_mottem_runtime_rti_keil_UVSocketJniJava_showUVISION
  (JNIEnv *, jobject);

/*
 * Class:     fzi_mottem_runtime_rti_keil_UVSocketJniJava
 * Method:    enterDebugMode
 * Signature: ()I
 */
JNIEXPORT jint JNICALL Java_fzi_mottem_runtime_rti_keil_UVSocketJniJava_enterDebugMode
  (JNIEnv *, jobject);

/*
 * Class:     fzi_mottem_runtime_rti_keil_UVSocketJniJava
 * Method:    exitDebugMode
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_fzi_mottem_runtime_rti_keil_UVSocketJniJava_exitDebugMode
  (JNIEnv *, jobject);

/*
 * Class:     fzi_mottem_runtime_rti_keil_UVSocketJniJava
 * Method:    setBreakpoint
 * Signature: (Ljava/lang/String;)Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_fzi_mottem_runtime_rti_keil_UVSocketJniJava_setBreakpoint
  (JNIEnv *, jobject, jstring);

/*
 * Class:     fzi_mottem_runtime_rti_keil_UVSocketJniJava
 * Method:    run
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_fzi_mottem_runtime_rti_keil_UVSocketJniJava_run
  (JNIEnv *, jobject);

/*
 * Class:     fzi_mottem_runtime_rti_keil_UVSocketJniJava
 * Method:    stop
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_fzi_mottem_runtime_rti_keil_UVSocketJniJava_stop
  (JNIEnv *, jobject);

/*
 * Class:     fzi_mottem_runtime_rti_keil_UVSocketJniJava
 * Method:    call
 * Signature: (II)V
 */
JNIEXPORT void JNICALL Java_fzi_mottem_runtime_rti_keil_UVSocketJniJava_call
  (JNIEnv *, jobject, jint, jint);

/*
 * Class:     fzi_mottem_runtime_rti_keil_UVSocketJniJava
 * Method:    runUntil
 * Signature: (J)V
 */
JNIEXPORT void JNICALL Java_fzi_mottem_runtime_rti_keil_UVSocketJniJava_runUntil
  (JNIEnv *, jobject, jlong);

/*
 * Class:     fzi_mottem_runtime_rti_keil_UVSocketJniJava
 * Method:    getValue
 * Signature: (JI)[B
 */
JNIEXPORT jbyteArray JNICALL Java_fzi_mottem_runtime_rti_keil_UVSocketJniJava_getValue
  (JNIEnv *, jobject, jlong, jint);

/*
 * Class:     fzi_mottem_runtime_rti_keil_UVSocketJniJava
 * Method:    setValue
 * Signature: (J[BI)V
 */
JNIEXPORT void JNICALL Java_fzi_mottem_runtime_rti_keil_UVSocketJniJava_setValue
  (JNIEnv *, jobject, jlong, jbyteArray, jint);

#ifdef __cplusplus
}
#endif
#endif
