/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class fzi_mottem_runtime_rti_vector_VectorXLWrapper */

#ifndef _Included_fzi_mottem_runtime_rti_vector_VectorXLWrapper
#define _Included_fzi_mottem_runtime_rti_vector_VectorXLWrapper
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     fzi_mottem_runtime_rti_vector_VectorXLWrapper
 * Method:    jniConnect
 * Signature: ()I
 */
JNIEXPORT jint JNICALL Java_fzi_mottem_runtime_rti_vector_VectorXLWrapper_jniConnect
  (JNIEnv *, jobject);

/*
 * Class:     fzi_mottem_runtime_rti_vector_VectorXLWrapper
 * Method:    jniDisconnect
 * Signature: (I)V
 */
JNIEXPORT void JNICALL Java_fzi_mottem_runtime_rti_vector_VectorXLWrapper_jniDisconnect
  (JNIEnv *, jobject, jint);

/*
 * Class:     fzi_mottem_runtime_rti_vector_VectorXLWrapper
 * Method:    jniSendMessage
 * Signature: (III[B)V
 */
JNIEXPORT void JNICALL Java_fzi_mottem_runtime_rti_vector_VectorXLWrapper_jniSendMessage
  (JNIEnv *, jobject, jint, jint, jint, jbyteArray);

/*
 * Class:     fzi_mottem_runtime_rti_vector_VectorXLWrapper
 * Method:    jniStartRxThread
 * Signature: (I)V
 */
JNIEXPORT void JNICALL Java_fzi_mottem_runtime_rti_vector_VectorXLWrapper_jniStartRxThread
  (JNIEnv *, jobject, jint);

#ifdef __cplusplus
}
#endif
#endif
