package fzi.mottem.runtime.interfaces;

public interface ITraceEvaluator
{
	/*
	 * The code for evaluation. Generated by PTSpec compiler.
	 * 
	 * Returns true if trace recording may be stopped and false otherwise.
	 */
	public boolean evaluateIsDone(ITrace trace);
}
