/*
 * IoHwA_API.h
 *
 *  Created on: Feb 17, 2016
 *      Author: lore_
 */

#ifndef EK_ECUA_IOHWA_API_H_
#define EK_ECUA_IOHWA_API_H_

#include "stm32f4_discovery.h"


//START_PICOSAR_API_SETTINGS
#define IOHWA_DISTANCE_IR //IOHWA_DISTANCE_US IOHWA_DISTANCE_IR
//END_PICOSAR_API_SETTINGS

//START_IOHWA_API_FUNKTIONS
#define SETTING_DISTANCE_INFRARED //SETTING_DISTANCE_ULTRASONIC SETTING_DISTANCE_INFRARED
#define ECU_GET_DISTANCE ECU_Get_Distance
////#define ECU_SET_SPEED(VALUE) ECU_Set_Speed(VALUE)
//STOP_IOHWA_API_FUNKTIONS



//START_PICOSAR_API_FUNCTIONS
uint32_t ECU_Get_Distance();
uint32_t ECU_Set_Speed(uint32_t value);
//END_PICOSAR_API_FUNCTIONS


#endif /* EK_ECUA_IOHWA_API_H_ */
